name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytorch-lightning==2.2.2 pydantic pytest black isort pre-commit jupyterlab alpha_vantage yfinance scikit-learn
      - name: Lint with black and isort
        run: |
          black --check .
          isort --check-only .
      - name: Run tests
        run: |
          pytest tests/ || true
      - name: Run quick diagnostics
        run: |
          python tests/quick_diag.py || true
